Storj/bridge-gui

Dockerfile
docker.build
docker.clean
docker.run
docker.runcluster
docker.stopall
scripts/install_deps_debian.sh

Docker updates

---

package.json
src/containers/Auth/SignupForm/signupValidation.js

For real this time

---

src/components/ErrorViews/FormLabelError.js
src/components/ErrorViews/formLabelError.js
src/components/ErrorViews/index.js
src/components/MessagePage/index.js
src/components/MessagePage/passwordResetPending.js
src/components/MessagePage/signupSuccess.js
src/components/index.js
src/containers/Auth/LoginForm/index.js
src/containers/Auth/LoginForm/loginValidation.js
src/containers/Auth/PasswordReset/index.js
src/containers/Auth/SignupForm/index.js
src/routes.js
src/utils/apiClient.js

User is at bridge-gui login page (click reset password link) —> user is taken to password reset form (type email and new password, and submit) —> user is taken to a confirmation page with a "check your email ..." message.
User gets the email, clicks the link which hits bridge api and then redirects back to bridge-gui login page. The login page shows a "success ... please log in." message (below).

Password Reset/Change #29

---

src/components/Copy/termsOfService.js
src/containers/App/App.scss
src/containers/App/index.js
src/containers/Auth/SignupForm/index.js

@boshevski I'd like your feedback on whether we should go with the scrolling-body modal or not. There is a small issue introduced by it which is that the scrollbar drops below/behind the `.modal-footer` section as you get to the bottom of the `.modal-body`.
[Demo screencapture (HD - youtube)](https://youtu.be/SyFfyAc1R84)

Terms of Service (Storage Terms)

---

.gitignore
Vagrantfile
src/containers/billing/billing.scss
src/containers/billing/index.js

added in a banner that notifies the user of the deactivated state of billing.

Stripe alert

---

src/components/referrals/send-referral-email.js
src/containers/referrals/index.js

Fixes a typo that prevented successful referral invite messages from showing up. Move messaging underneath button.

Referrals validation

---

src/components/billing/add-card-panel.js

Whether or not we want to collect this form, I don't think it belongs on the Billing page. 
If we want to collect this info, it should be in a sign up flow, or on a user profile page. 
This PR removes it from the Billing page.

Remove Your Details form from Card View

---

src/components/referrals/send-referral-email.js
src/containers/referrals/index.js

Multiple results are spaced better

Prettier results

---

src/containers/auth/signup-form/index.js

Add Missing Spaces in Sign Up

---

src/containers/auth/login-form/index.js
src/containers/billing/index.js
src/containers/referrals/index.js

Fixes: 
2. referralLink not loading properly on first load for logged in users
3. billing and referral routes are loading even if user is not authenticated

Referral fixes

---

src/components/referrals/referral-info.js
src/components/referrals/send-referral-email.js
src/containers/referrals/index.js

Fixes: 7. error and success messages don't disappear after sending referral email, and updates referral program info copy.

Ui updates

---

src/components/billing/add-card-panel.js

Update billing page

---

src/containers/billing/index.js
src/containers/dashboard/index.js

Refetches Apollo queries when component mounts, making sure data is rendered appropriately.
Fixes #128

Refetch billing queries

---

src/containers/billing/add-card-form.js
src/containers/billing/index.js
src/containers/dashboard/index.js

Shows errors for Add Card Form. Errors from Stripe weren't being caught in the callback.

Show Add Card Form errors

---

package.json
src/components/billing/payment-info-panel.js
src/containers/billing/add-card-form.js
src/containers/billing/index.js
yarn.lock

Haven't figured out how to get `refetch()` to work. Data is being cached and new fetches aren't happening. I've tried putting in `forceFetch: true` but I may not be putting it in the right place. Subsequent releases of `react-apollo` fix this but there are major API changes that go along with going this route.
Quick fix would be to force a `window.location.reload()`.
If we can't get `refetch()` to work, that would be my vote, at least as a temporary fix. It's not an action that a user should be doing very much.

Fix remove card

---

src/components/billing/payment-info-panel.js
src/containers/billing/index.js

Add back in remove card logic from a weird merge. Also did some linting and cleanup.

Add back in remove card logic

---

src/components/billing/balance-panel.js
src/components/billing/currency.js
src/components/billing/transactions-list.js
src/components/billing/usage-panel.js
src/components/billing/usage-panel.scss
src/containers/billing/index.js
src/redux/modules/transaction-group.js
src/utils/index.js

Prettifies things for the user.

Make balance, bandwidth, and storage amounts pretty

---

package.json
src/components/billing/balance-panel.js
src/components/billing/usage-panel.js
yarn.lock

UI changes. Also need to force bridge-gui to rebuild on staging to see if the `isValidUTF8` error is still there.

Billing and utf8

---

src/components/billing/add-card-panel.js
src/components/billing/payment-info-panel.js
src/components/file-list/index.js
src/containers/buckets/file-bucket.js
src/utils/api-client.js

I think this `resolveFileFromPointer` is the thing actually using the WebSocket and making it mess up. We're not even using this function though, so maybe if we take it out it will fix staging?

Remove all refs to getFile method that uses WebSocket

---

src/components/billing/add-card-panel.js
src/components/billing/balance-panel.js
src/components/billing/payment-info-panel.js
src/components/billing/usage-panel.js
src/components/billing/usage-panel.scss

Style, layout, and responsiveness fixes on billing page.

Billing page updates
